name: Build Project Matrixx Kernel (Veux) 3
on: 
  workflow_dispatch:
      inputs:
        ref:
          type: string
          description: reference head
          required: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout local repository
      uses: actions/checkout@v4
      with:
        path: builder

    - name: Checkout kernel source
      uses: actions/checkout@v4
      with:
        repository: Lu5ck/kernel_xiaomi_sm6375
        path: source
        ref: ${{ github.event.inputs.ref }}

    - name: Hello Docker
      uses: ./builder/actions/veux
