name: Build Project Matrixx Kernel (Veux) 2
on: 
  workflow_dispatch:
      inputs:
        ref:
          type: string
          description: reference head
          required: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Maximize build space
      uses: lu5ck/maximize-build-space@master
      with:
        remove-dotnet: true
        remove-android: true
        remove-haskell: true
        remove-codeql: true
        root-reserve-mb: 30000
        swap-size-mb: 24576

    - name: Checkout kernel source
      uses: actions/checkout@v4
      with:
        repository: Lu5ck/kernel_xiaomi_sm6375
        ref: ${{ github.event.inputs.ref }}

    - name: Checkout zipper
      uses: actions/checkout@v4
      with:
        repository: lu5ck/AnyKernel3-CrDorid-PocoX3Pro
        path: zipper
        ref: veux

    - name: Android kernel build
      uses: lu5ck/android-kernelsu-actions@master
      id: build
      env:
        NAME: CrDroid-KernelSU
      with:
        arch: arm64
        compiler: aosp-clang/master/clang-r498229b
        defconfig: vayu_user_defconfig
        image: Image.gz-dtb
        usekprobe: no

    - name: Generate Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Flashable Kernel
        path: ${{ github.workspace }}/zipper/${{ steps.build.outputs.outfile }}
