name: Build Project Matrixx Kernel (Veux)
on: 
  workflow_dispatch:
      inputs:
        ref:
          type: string
          description: reference head
          required: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Maximize build space
      uses: lu5ck/maximize-build-space@master
      with:
        remove-dotnet: true
        remove-android: true
        remove-haskell: true
        remove-codeql: true
        root-reserve-mb: 30000
        swap-size-mb: 24576

    - name: "Install prerequisites"
      run: |
        sudo apt-get install -y patchelf

    - name: Checkout kernel source
      uses: actions/checkout@v4
      with:
        repository: Lu5ck/kernel_xiaomi_sm6375
        ref: ${{ github.event.inputs.ref }}

    - name: "Get latest KernelSU"
      working-directory: ${{ github.workspace }}
      run: |
          # Remove KSU, if any
          sudo rm -rf "./drivers/kernelsu"
          ls drivers/

          # Download latest KSU
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main

    - name: "Build glibc 2.39"
      working-directory: ${{ github.workspace }}
      run: |
          wget -c https://ftp.gnu.org/gnu/glibc/glibc-2.39.tar.gz
          tar -zxvf glibc-2.39.tar.gz && cd glibc-2.39
          mkdir glibc-build && cd glibc-build
          ../configure --prefix=/opt/glibc
          make
          make install
